# Generated by Django 4.1.6 on 2023-05-31 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(max_length=255, null=True)),
                ('player_name', models.CharField(max_length=255, null=True)),
                ('attempts', models.IntegerField(default=10)),
            ],
        ),
        migrations.CreateModel(
            name='TimeCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(max_length=255, null=True)),
                ('name_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='main.player')),
            ],
        ),
    ]
