# Generated by Django 4.1.6 on 2023-06-02 21:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_player_phone_number_alter_player_attempts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timecount',
            name='name_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='times', to='main.player'),
        ),
    ]
