# Generated by Django 4.1.6 on 2023-06-02 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_timecount_name_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='timecount',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
